---
keys:
  - &scotte age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
  - &hera age1y5775nrh792zh2z4c8xpxf432e5xdwj03g4lgvcuv69zrzk0ju0qfruczz
  - &nixvm age1m3tvwul5aum8vw98h3ughratrsnmkyhkj02ghcwysnhmg5k2ufzq5s2pkn

creation_rules:
  - path_regex: .*\.sops\.yaml$
    key_groups:
      - age:
          - *scotte
          - *hera
          - *nixvm
