---
keys:
  - &scotte age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
  - &nixvm age1m3tvwul5aum8vw98h3ughratrsnmkyhkj02ghcwysnhmg5k2ufzq5s2pkn

creation_rules:
  - path_regex: .*\.sops\.yaml$
    key_groups:
      - age:
          - *scotte
          - *nixvm
