---
version: "3"

includes:
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops

tasks:
  fix-git:
    desc: Set the git remote URL to be used via ssh
    silent: true
    cmds:
      - git remote set-url origin git@github.com:szinn/nix-config.git

  default:
    silent: true
    cmds:
      - task -l

  pc-init:
    desc: Initialize pre-commit hooks
    cmds:
      - pre-commit install --install-hooks

  pc-update:
    desc: Update pre-commit dependencies
    cmds:
      - pre-commit autoupdate

  pc-run:
    desc: Run pre-commit
    cmds:
      - pre-commit run --all-files
