{ config, lib, pkgs, imports, modulesPath, ... }:

with lib;
{
  # NOTE
  # Some 'global' areas have defaults set in their respective modules.
  # These will be applied when the modules are loaded
  # Not the global role.
  # Not sure at this point a good way to manage globals in one place
  # without mono-repo config.

  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-config-generate
      ./global
    ];

  config = {

    boot.tmp.cleanOnBoot = true;

    mySystem = {

      # basics for all devices
      time.timeZone = "Europe/Amsterdam";
      security.increaseWheelLoginLimits = true;
      system.packages = [ pkgs.bat ];
      domain = "nnhome.eu";
      internalDomain = "nnhome.eu";

      shell.fish.enable = true;
      # But wont enable plugins globally, leave them for workstations
      system.resticBackup.remote.location = "s3:s3.eu-central-003.backblazeb2.com/nixos-restic";
    };

    environment.systemPackages = with pkgs; [
      attic-client
      curl
      wget
      dnsutils
      tree
    ];

    networking.useDHCP = lib.mkDefault true;
    networking.domain = config.mySystem.domain;
  };

}
