# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  adguard-exporter = {
    pname = "adguard-exporter";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "henrywhitaker3";
      repo = "adguard-exporter";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-OltYzxBOOcaW3oYNFvxxjG1qRvuLaZfReSeQaNGiRDc=";
    };
  };
  chrony-exporter = {
    pname = "chrony-exporter";
    version = "v0.12.1";
    src = fetchFromGitHub {
      owner = "SuperQ";
      repo = "chrony_exporter";
      rev = "v0.12.1";
      fetchSubmodules = false;
      sha256 = "sha256-S5Mox5HmOJ+PiV6aq/tqubf6kfOdOMvvUk+m0VzOdl0=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "824f1fb9b3d697359e0be1f5a4d7086f49206cac";
    src = fetchFromGitHub {
      owner = "cockpit-project";
      repo = "cockpit-podman";
      rev = "824f1fb9b3d697359e0be1f5a4d7086f49206cac";
      fetchSubmodules = false;
      sha256 = "sha256-vEDZumF3hN6wLC97cx6OAHwbEYguLEIHzl7FNpfmcOE=";
    };
    date = "2025-11-20";
  };
  cosmic-idle = {
    pname = "cosmic-idle";
    version = "983d34ad9644930495e6d1c3ffb78408dad0c78d";
    src = fetchFromGitHub {
      owner = "pop-os";
      repo = "cosmic-idle";
      rev = "983d34ad9644930495e6d1c3ffb78408dad0c78d";
      fetchSubmodules = false;
      sha256 = "sha256-qVrcMI7sr0mWyYW1fM6oP/6qKEhlqqyQ/WiJaWfCQPU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cosmic-idle-983d34ad9644930495e6d1c3ffb78408dad0c78d/Cargo.lock;
      outputHashes = {
        "clipboard_macos-0.1.0" = "sha256-+8CGmBf1Gl9gnBDtuKtkzUE5rySebhH7Bsq/kNlJofY=";
        "atomicwrites-0.4.2" = "sha256-QZSuGPrJXh+svMeFWqAXoqZQxLq/WfIiamqvjJNVhxA=";
        "cosmic-settings-config-0.1.0" = "sha256-WLZJx8FwseCD7hHU60+HekNBxUE6B/6HRhP8oqokTNI=";
        "cosmic-config-0.1.0" = "sha256-Xj5b0X3IKI3sNKJrQeIhnmAV8BOKZTNh5rcn1irqWlY=";
        "smithay-clipboard-0.8.0" = "sha256-4InFXm0ahrqFrtNLeqIuE3yeOpxKZJZx+Bc0yQDtv34=";
        "upower_dbus-0.3.2" = "sha256-3QCkl2/kof0l8S3zAppEWL88uaXAH43NL4UJA0xVCPI=";
      };
    };
    date = "2025-11-13";
  };
  flux-local = {
    pname = "flux-local";
    version = "8.0.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/f/flux_local/flux_local-8.0.1.tar.gz";
      sha256 = "sha256-1M0NdlqNgYL+8HCvKMD6FVXJjX80U2dzSB7nEuTCw2Q=";
    };
  };
  gpsd-prometheus-exporter = {
    pname = "gpsd-prometheus-exporter";
    version = "6a6009c8f89874eef46690abd96cf6f1d1149d9f";
    src = fetchFromGitHub {
      owner = "brendanbank";
      repo = "gpsd-prometheus-exporter";
      rev = "6a6009c8f89874eef46690abd96cf6f1d1149d9f";
      fetchSubmodules = false;
      sha256 = "sha256-oR+JNwf+QqWzreL0qzsxOqMCWZxFma4zREnAcToGkdY=";
    };
    date = "2025-08-09";
  };
  mqtt-explorer = {
    pname = "mqtt-explorer";
    version = "v0.3.5";
    src = fetchFromGitHub {
      owner = "thomasnordquist";
      repo = "MQTT-Explorer";
      rev = "v0.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-lXHPKOZh5gbG+kpH9wLBcHztS7fBj9D57ySKd1xkhxc=";
    };
  };
  npiperelay = {
    pname = "npiperelay";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "jstarks";
      repo = "npiperelay";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-cg4aZmpTysc8m1euxIO2XPv8OMnBk1DwhFcuIFHF/1o=";
    };
  };
  talosctl = {
    pname = "talosctl";
    version = "v1.10.8";
    src = fetchFromGitHub {
      owner = "siderolabs";
      repo = "talos";
      rev = "v1.10.8";
      fetchSubmodules = false;
      sha256 = "sha256-WON2jQi8so3qZDsXVavGgSqUGBXmAYSYTdqo1o6+olk=";
    };
  };
}
