---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Docs"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/docs.yaml
      - docs/**
      - README.md

permissions:
  actions: write
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@6c406e8a244fdf6bbf79e6cc8a91504a48d2c2ce # v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
        with:
          token: "${{ steps.app-token.outputs.token }}"
          enablement: true

      - name: Build docs
        uses: docker://ghcr.io/bjw-s/mdbook:0.4.37@sha256:aa9e2ef5ef4f59829d4134cf0ee34340ba1ba6d4579e1850e39bc651c2d09a89
        with:
          args: mdbook build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./docs/book/html

  publish:
    name: Publish Docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@6c406e8a244fdf6bbf79e6cc8a91504a48d2c2ce # v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        with:
          token: "${{ steps.app-token.outputs.token }}"
