---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Nix Flake Actions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  nix-build:
    strategy:
      fail-fast: false # let it build all the targets
      matrix:
        include:
          - system: mavy-wsl
            os: arc-runner-set-nix-config
          - system: peppernuts
            os: arc-runner-set-nix-config
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Install xz-utils
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y xz-utils;
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
        with:
          extra_nix_config: |
            auto-optimise-store = true
            system-features = nixos-test benchmark big-parallel kvm
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        if: ${{ !github.event.pull_request.head.repo.fork }}
        env:
          USER: runner
        with:
          name: mavy
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix build \
            --print-build-logs \
            --builders "" \
            --max-jobs 2 \
            --eval-store auto \
            ".#ciSystems.${{ matrix.system }}"

  nix-build-success:
    if: ${{ always() }}
    needs:
      - nix-build
    name: Nix Build Successful
    runs-on: arc-runner-set-nix-config
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        name: Check matrix status
        run: exit 1
