---
name: Build and diff Nix systems
permissions:
  pull-requests: write
  contents: read
on:
  pull_request:
    paths:
      - .github/workflows/**
      - "**.nix"
      - "flake.lock"

env:
  nix-conf: |-
    access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    auto-optimise-store = true
    experimental-features = nix-command flakes
    system-features = nixos-test benchmark big-parallel kvm
    fallback = true # build from source if a binary substitute fails
    # substituters = https://cache.garnix.io https://cache.nixos.org/ https://nix-cache.heimat.dev https://nix-community.cachix.org
    substituters = https://cache.garnix.io https://cache.nixos.org/ https://nix-community.cachix.org
    trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
    extra-platforms = aarch64-linux
    builders-use-substitutes = true

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: "Build ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mavy-wsl
            os: arc-runner-set-nix-config
          - target: peppernuts
            os: arc-runner-set-nix-config
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Install xz-utils
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y xz-utils;

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: ${{ env.nix-conf }}

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Garbage collect build dependencies
        run: nix-collect-garbage

      - name: Build previous ${{ matrix.target }} system
        run: nix build github:nnmavy/nix-config#ciSystems.${{ matrix.target }} -v  --log-format raw --profile ./profile

      - name: Build new ${{ matrix.target }} system
        run: |
          set -o pipefail
          nix build .#ciSystems.${{ matrix.target }}  --profile ./profile --show-trace --fallback -v --log-format raw > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)

      - name: Output build failure
        if: failure()
        run: |
          drv=$(grep "For full logs, run" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv")
          if [ -n $drv ]; then
            nix log $drv
            echo $drv
          fi
          exit 1

      - name: Diff profile
        id: diff
        run: |
          nix profile diff-closures --profile ./profile
          delimiter="$(openssl rand -hex 16)"
          echo "diff<<${delimiter}" >> "${GITHUB_OUTPUT}"
          nix profile diff-closures --profile ./profile | perl -pe 's/\e\[[0-9;]*m(?:\e\[K)?//g' >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Scan for security issues
        id: security
        run: |
          nix run nixpkgs/nixos-unstable#vulnix -- -w https://raw.githubusercontent.com/ckauhaus/nixos-vulnerability-roundup/master/whitelists/nixos-unstable.toml ./profile | tee /tmp/security.txt
          OUTPUT_SECURITY="$(cat /tmp/security.txt)"
          OUTPUT_SECURITY="${OUTPUT_SECURITY//'%'/'%25'}"
          OUTPUT_SECURITY="${OUTPUT_SECURITY//$'\n'/'%0A'}"
          OUTPUT_SECURITY="${OUTPUT_SECURITY//$'\r'/'%0D'}"
          echo "$OUTPUT_SECURITY"

          delimiter="$(openssl rand -hex 16)"
          echo "security<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$OUTPUT_SECURITY" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Comment report in pr
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ !startswith(github.ref, 'dependabot') }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: ".#top.${{ matrix.target }}"
          message: |
            ### Report for `${{ matrix.target }}`

            <summary> Version changes </summary> <br>
            <pre> ${{ steps.diff.outputs.diff }} </pre>

            <details>
            <summary> Security vulnerability report </summary> <br>
            <pre> ${{ steps.security.outputs.security }} </pre>
            </details>

# Liberated from edeneast's github
