---
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: ["main"]
    paths:
      - .github/renovate-bot.json5
      - .github/renovate.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

jobs:
  renovate:
    name: Renovate
    runs-on: docker
    container:
      image: ghcr.io/renovatebot/renovate:latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4.1.1
        with:
          token: ${{ secrets.TOKEN }}
      - name: Run Renovate
        run: renovate
        env: 
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_GITEA_TOKEN}}
          RENOVATE_DRY_RUN: false
          RENOVATE_CONFIG_FILE: .github/renovate-bot.json5
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ gitea.repository }}"
          GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
